# Generated by Django 3.2.7 on 2021-10-08 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asociacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('poblacion', models.IntegerField()),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamento', to='comunidadesIndigenasApp.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Resguardo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('poblacion', models.IntegerField()),
                ('texto', models.TextField()),
                ('id_asociacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asociacion', to='comunidadesIndigenasApp.asociacion')),
                ('id_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio', to='comunidadesIndigenasApp.municipio')),
            ],
        ),
    ]
