from .asociacionSerializer import AsociacionSerializer
from .departamentoSerializer import DepartamentoSerializer
from .municipioSerializer import MunicipioSerializer
from .resguardoSerializer import ResguardoSerializer